### ISSUE TITLE
[Feature request] Make design consistent with libadwaita

### ISSUE THREAD

**Issue by somepaulo** [qwreey75/quick-settings-tweaks#59]
It would be great to have an option to make the Quick Settings look more like libadwaita: with less border-radius.

![quicksettings](https://user-images.githubusercontent.com/15643750/206511561-70d68024-d7b0-4bec-905a-874ac9fbba36.gif)

Here's the code that does it in `gnome-shell.css`:
```css
/* Quick Settings */
.quick-settings {
  padding: 12px;
  border-radius: 20px; }
.quick-toggle {
  border-radius: 12px;
  border: none; } /* I want to add borders like on the notifications and calendar popover but it is such a subtle difference I just won't bother with it */
.quick-menu-toggle .quick-toggle-arrow:ltr {
    border-radius: 0 12px 12px 0; }
.quick-menu-toggle .quick-toggle-arrow:rtl {
    border-radius: 12px 0 0 12px; }
.quick-toggle-menu {
  background-color: #353535;
  border-radius: 8px;
  padding: 12px;
  margin: 12px 12px 0; }
```
